[SDK-545] Name change for deprecated calls
Countly/countly-sdk-web pull request #148
Opened 2021-11-16 15:37 UTC by turtledreams

- Changed `report_feedback` to `recordRatingWidgetWithID`. Now old call redirects to the new one.
- Changed `show_feedback_popup` to `presentRatingWidgetWithID`. Now old call redirects to the new one.
- Changed `initialize_feedback_popups` to `initializeRatingWidgets`. Now old call redirects to the new one.
- Changed `enable_feedback` to `enableRatingWidgets`. Now old call redirects to the new one.
- Changed `report_conversion` to `recordDirectAttribution`. Now old call redirects to the new one.
- Fixed some places where deprecated call was used. Changed with new one.
- Added changelog entries

2021-11-16 16:33 UTC, ArtursKadikis requested changes

2021-11-16 16:33 UTC, ArtursKadikis commented on lib/countly.js
> +        * @param {Object} feedback - object with feedback properties
rename the function variable to "ratingWidget" and respectively also the name used in code comments from "feedback" to "ratingWidget".

2021-11-16 16:33 UTC, ArtursKadikis commented on lib/countly.js
> +        * @param {string} id - id value of related feedback widget, you can get this value by click "Copy ID" button in row menu at "Feedback widgets" screen
rename "feedback widget" to "rating widget"

2021-11-16 16:33 UTC, ArtursKadikis commented on lib/countly.js
> +        * Prepare widgets according current options
"Prepare **rating** widget"

2021-11-16 16:33 UTC, ArtursKadikis commented on lib/countly.js
> +        * Show feedback popup by passed widget ids array
"Show **rating widget** popup"

2021-11-16 16:33 UTC, ArtursKadikis commented on samples/react/src/Location-WithEffect.js
>      // Initialize feedback popup by current page/pathname
"Initialize **rating widget** popup"

2021-11-16 16:33 UTC, ArtursKadikis commented on lib/countly.js
> +        this.recordRatingWidgetWithID = function(feedback) {
In the function bellow, replace mentions and usages of "Feedback" to "Rating widget"

2021-11-17 09:59 UTC, ArtursKadikis commented
Paging dr @ar2rsawseen to check this patient out

2021-11-17 12:17 UTC, ar2rsawseen commented
Well, the only problem I have is that some public methods are now camelCase and others are Snake_case :D 
It is part of uniting API of all SDKs?

Then you should better come up with united API first and then change all methods in one swoop, while providing backwards compatibility for web SDK cases?

But other than that, its fine

2021-11-17 12:17 UTC, ar2rsawseen approved these changes

2021-11-18 22:05 UTC, merged