[SDK-364] Internal Limits
Countly/countly-sdk-web pull request #149
Opened 2021-11-18 07:59 UTC by turtledreams

- Created 2 internal functions:

1. `truncateSingleValue` takes a single string or number and truncates it for a given limit, for example:
     `truncateSingleValue('abcd', 2)` will return `'ab'`
     and also it will create a log informing the user that the value is over the limit and will be truncated.
2. `truncateObject` takes an object and returns a new object with truncated key value pairs, for example:
     `truncateObject({'ab':'1234'}, 1, 2)` will return `{'a':'12'}`
     and also it will create a log informing the user that the key/value is over the limit and will be truncated.

- Used these functions to enforce internal limits where it seemed fit, especially segmentations and event creation.
- Limit values are set at init time, except the internal one (`maxStackTraceThreadCount`)
- Erased/Renamed `max_logs` with `max_breadcrumb_count`
- Added their respective comments except for `maxStackTraceThreadCount`
- Used regex to limit stack trace line limits.
- Performed unit tests on regex and functions individually. 
- Changed `srcElement` with `target` as it was deprecated
- Added changelog entry (was not sure about labeling, maybe potentially/minor breaking change)

2021-11-18 08:35 UTC, ArtursKadikis requested changes
Leave "max_logs" in. To get the resulting maxBreadcrumbCount value, you would check both breadcrumb values. If one of them is set, you would use that value. If both of them are set, you would use "maxBreadcrumbCount". If none of them are set, you would use the default for "maxBreadcrumbCount".

"max_logs" would need to be deprecated.

All of these limits would need to be described in the doc.

2021-11-18 08:35 UTC, ArtursKadikis commented on CHANGELOG.md
> +- Multiple values now have a default limit adjustable at initialization:
mark this as minor breaking change

2021-11-18 08:35 UTC, ArtursKadikis commented on lib/countly.js
> +        if (str.length > limit && (typeof str === 'string' || typeof str === 'number')) {
Type check would probably need to come first. I think it would throw an exception if you would call ".length" on a number or boolean.

2021-11-18 08:35 UTC, ArtursKadikis commented on lib/countly.js
> +            if (key.length > keyLimit) {
type of key need to be checked

2021-11-18 08:35 UTC, ArtursKadikis commented on lib/countly.js
> +            if (obj[key].length > valueLimit && (typeof obj[key] === 'string' || typeof obj[key] === 'number')) {
would probably need similar early type checking as described for "truncateSingleValue"

2021-11-18 08:35 UTC, ArtursKadikis commented on lib/countly.js
> +                var errorRegex = new RegExp("(?!$|\n)([^\n]{" + this.maxStackTraceLineLength + "}(?!\n))", "g");
No need for regex. Let's keep it simple with loops and function calls.

2021-11-23 19:52 UTC, ArtursKadikis requested changes
This also requires a sample app/page where this is tested. That would test all values to make sure that all possible limits are enforced.

Current  breadcrumb login does not work like discussed. It should check if 'max_logs' has a value set. If it has, it should use that. If both are set, it should use "maxBreadcrumbCount".

From line 921 to line 1025 all "this.debug" calls should be replaced with "self.debug" as they would be linking to the context of surounding object where they are set.

To reduce the chance of potential future errors and consistency, use "self.XXX" instead of "this.XXX" when referencing "global" things. This currently looks to be only required for "this.debug" references.

Both "truncateSingleValue" and "truncateObject" need to be simplified. They also miss a few things discussed previously. 
In the single value call you would do the "number" check first, and if it would be a number, then you would only cast it to string and nothing else (basicly only lines 3560 - 3561. After that it would check the string type check. This way you get rid of duplicate code and make it more compact. 
In "truncateObject" for both the key and value you just call "truncateSingleValue", as that already has all of the required functionality.

2021-11-23 19:52 UTC, ArtursKadikis commented on lib/countly.js
> +            maxStackTraceThreadCount = 30,
why is this set?

2021-11-23 19:52 UTC, ArtursKadikis requested changes
This also requires a sample app/page where this is tested. That would test all values to make sure that all possible limits are enforced.

Current  breadcrumb login does not work like discussed. It should check if 'max_logs' has a value set. If it has, it should use that. If both are set, it should use "maxBreadcrumbCount".

From line 921 to line 1025 all "this.debug" calls should be replaced with "self.debug" as they would be linking to the context of surounding object where they are set.

To reduce the chance of potential future errors and consistency, use "self.XXX" instead of "this.XXX" when referencing "global" things. This currently looks to be only required for "this.debug" references.

Both "truncateSingleValue" and "truncateObject" need to be simplified. They also miss a few things discussed previously. 
In the single value call you would do the "number" check first, and if it would be a number, then you would only cast it to string and nothing else (basicly only lines 3560 - 3561. After that it would check the string type check. This way you get rid of duplicate code and make it more compact. 
In "truncateObject" for both the key and value you just call "truncateSingleValue", as that already has all of the required functionality.

2021-11-24 08:01 UTC, turtledreams commented
- Added example file
- Fixed and tested breadcrumbs
- Usage of `this` is fixed
- `typeof` check is now shorter
- `truncateSingleValue` is now re-used in `truncateObject`
- All tested with example

2021-11-24 12:23 UTC, ArtursKadikis requested changes
"maxBreadcrumbCount" value setting logic should be moved to init.

Test should be tweaked:
* add explicit event recording that will be truncated
* add user profile value recording that will be truncated
* for user profiless use also some property modiffier

Add square brackets to printed values

2021-11-24 16:31 UTC, turtledreams commented
- `maxBreadcrumbCount`  setting logic moved to init
- Added user profile value recording 
- Added all property modifiers
- Added square brackets to printed values
- Fixed an issue where only internal events were passing `add_event`
- Changelog entry set to 21.11.0

2021-11-25 11:23 UTC, ArtursKadikis requested changes

2021-11-25 11:23 UTC, ArtursKadikis commented on lib/countly.js
> +                log('a');
seems like a dev log which should be removed

2021-11-25 11:23 UTC, ArtursKadikis commented on lib/countly.js
> +                log('b');
seems like a dev log which should be removed

2021-11-25 11:23 UTC, ArtursKadikis commented on lib/countly.js
> +            if (event.key in internalEventKeyEnums) {
should be reworked, as this would add a performance penalty

2021-11-25 11:23 UTC, ArtursKadikis commented on examples/example_internal_limits.html
> +          stack: "Enter your\n error here\n separated\n with newlines\n",
add more lines so that it is more pronounced that it is truncated

2021-11-25 11:23 UTC, ArtursKadikis commented on examples/example_internal_limits.html
> +          name: "Arturs Sosins",
probably better us some other name :D

2021-11-25 11:23 UTC, ArtursKadikis commented on examples/example_internal_limits.html
> +          username: "ar2rsawseen",
same with this username

2021-11-25 11:23 UTC, ArtursKadikis commented on examples/example_internal_limits.html
> +            "https://pbs.twimg.com/profile_images/1442562237/012_n_400x400.jpg",
and also this picture link :D

2021-11-25 11:23 UTC, ArtursKadikis commented on examples/example_internal_limits.html
> +          custom: {
have 10 custom keys

2021-11-25 11:23 UTC, ArtursKadikis commented on examples/example_internal_limits.html
> +      function set() {
these modification calls should be reworked so that each of them breaks the set limits

2021-11-25 11:23 UTC, ArtursKadikis commented on examples/example_internal_limits.html
> +          segmentation: {
this should have 10 segmentation values

2021-11-25 21:32 UTC, ArtursKadikis commented
@ar2rsawseen and @itsiprikshit , could you please have a look to see if you notice any issues?

2021-11-26 16:11 UTC, ar2rsawseen approved these changes

2021-11-29 06:50 UTC, itsiprikshit approved these changes

2021-11-29 14:56 UTC, merged