[SDK-562] Focus Fix
Countly/countly-sdk-web pull request #151
Opened 2021-11-23 16:28 UTC by turtledreams

-Fixed a bug where session request were sent while browser was out of focus
- `track_session` was only following tab change and minimization, now it also checks change in focus
- Tested on : Firefox, Chrome, Opera, Edge, Firefox (Mobile)

2021-11-23 20:37 UTC, ArtursKadikis requested changes

2021-11-23 20:37 UTC, ArtursKadikis commented on CHANGELOG.md
> +- Bug Fix - Fixed a bug where sessions were restarting even browser was out of focus
Are sessions "restarting" or just the duration counter/timer is not paused?

2021-11-23 20:37 UTC, ArtursKadikis commented on lib/countly.js
> +                    log("stopped time");
Add "onchange, " to the start of this log

2021-11-23 20:37 UTC, ArtursKadikis commented on lib/countly.js
> +                    log("started time");
Add "onchange, " to the start of this log

2021-11-24 10:08 UTC, ArtursKadikis commented
@ar2rsawseen does this look ok?

2021-11-24 17:15 UTC, ar2rsawseen approved these changes

2021-11-25 11:09 UTC, merged