[feedback-widget-combine] added rating support to present_feedback_wi…
Countly/countly-sdk-web pull request #155
Opened 2021-12-01 19:25 UTC by frknbasaran

…dget() method.

2021-12-02 13:18 UTC, ArtursKadikis requested changes
Reapply code styling according to the SDK's lint file.

2021-12-02 13:18 UTC, ArtursKadikis commented on lib/countly.js
> +            function showRating(feedback) {
Rename to "showRatingForFeedbackWidget"

2021-12-02 13:18 UTC, ArtursKadikis commented on lib/countly.js
> +             * Function to prepare rating sticker and popup
Comment should also mention feedback widget

2021-12-02 13:18 UTC, ArtursKadikis commented on lib/countly.js
> +                    switch (presentableFeedback.showPolicy) {
this switch can be simplified

2021-12-02 13:18 UTC, ArtursKadikis commented on lib/countly.js
> +                            if (document.readyState === "complete") {
Refactor this. Make it better

2021-12-02 13:18 UTC, ArtursKadikis commented on lib/countly.js
> +                loadCSS(this.url + '/surveys/stylesheets/countly-surveys.css');
Move into the "widgetFamily" "if" statement

2022-01-04 13:32 UTC, ArtursKadikis commented
@turtledreams test this in a sample app and double check that all widget types and was to use them are working. That means 4 different scenarios:
* old rating widget approach. 
* new rating widget approach with the feedback widget mechanisms. Be sure not to use any calls from the old approach.
* surveys
* nps

2022-02-01 10:08 UTC, turtledreams approved these changes

2022-02-01 10:08 UTC, turtledreams commented on lib/countly.js
> +                else if (presentableFeedback.type === "rating") {
perfect

2022-02-01 13:18 UTC, merged