[SDK-702] device id type function and tests
Countly/countly-sdk-web pull request #181
Opened 2022-03-01 11:38 UTC by turtledreams

On going, not finished.

2022-03-21 14:47 UTC, ArtursKadikis requested changes
Device ID type call should return enum. There should be enum values to compare to. Write doc entry.

2022-03-21 14:47 UTC, ArtursKadikis commented on cypress/integration/device_id.js
> +device ID types:
move these

2022-03-21 14:47 UTC, ArtursKadikis commented on cypress/integration/device_id.js
> +function idType() {
probably not needed, just use the call, Luke!

2022-03-21 14:47 UTC, ArtursKadikis commented on cypress/support/helper.js
> +function giveInitObj(specs) {
kill this abomination

2022-03-21 14:47 UTC, ArtursKadikis commented on lib/countly.js
> +        this.check_device_id_type = function() {
it should be "get_device_id_type"

2022-04-04 15:06 UTC, turtledreams commented
Tests are modified. Also currently it seems to be the order of deviceID setting power is like this:
 URL>OFFLINE>USERSET>AUTOGEN. 
Will check our chart and will comment here again if it is proper.
To be continued...

2022-04-19 12:11 UTC, ArtursKadikis requested changes
Add 8 tests in 2 pairs of 4, and then change device ID or enter offline mode and then change id

2022-04-26 11:43 UTC, ArtursKadikis approved these changes

2022-04-26 11:43 UTC, merged