[803] detect_device function simplified
Countly/countly-sdk-web pull request #213
Opened 2022-06-19 12:21 UTC by turtledreams

2022-06-19 12:22 UTC, turtledreams commented
cant recall is_bot, ua_raw thingy, lets chat again

2022-06-21 10:06 UTC, turtledreams commented
made it so that user agent related information can be processed from a single place and accessed from there. However still looks messy, might assign each value to their own function

2022-06-27 15:09 UTC, ArtursKadikis requested changes
divide this into 3 different calls

2022-06-28 08:39 UTC, turtledreams commented
current tests:

![image](https://user-images.githubusercontent.com/62231246/176134412-726b82fe-bef5-493d-a099-8d2514ff141e.png)

2022-06-29 13:28 UTC, turtledreams commented on lib/countly.js
> +    function detect_device(uaOverride) {
indicate user agent is used

2022-06-29 13:28 UTC, turtledreams commented on lib/countly.js
> +    function is_bot(uaOverride) {
user agent is used

2022-06-29 15:12 UTC, ArtursKadikis approved these changes

2022-06-29 15:12 UTC, merged